import type { Metadata } from 'next';
import SeoLandingPage from '@/components/SeoLandingPage';

export const metadata: Metadata = { title: 'Website Color Picker for Chrome', description: 'Collect colors from a website, build a reusable site palette, and compare brand references with TokenTint for Chrome.', alternates: { canonical: '/website-color-picker', languages: { en: '/website-color-picker', 'zh-CN': '/zh-CN/website-color-picker', 'x-default': '/website-color-picker' } } };

export default function Page() { return <SeoLandingPage
  h1="Website Color Picker for Chrome"
  intro="Collect the colors from a reference page, turn them into a reusable project palette, and keep the visual reference close while you design or rebuild an interface."
  problem="When a website is your reference, one-off color picks are not enough. Brand colors, surfaces, borders, text, and accents are spread across the page, making competitor analysis and visual refresh work difficult to track."
  solution="TokenTint lets you sample colors from a reference website, review them together in history, and save the useful set to a project palette. For broader research, Pro can extract key page colors so you can start from a palette instead of clicking every color one at a time."
  workflowTitle="From a reference website to a working palette."
  workflowKickers={['COLLECT', 'COMPARE', 'SAVE']}
  workflow={['Collect. Sample the brand, background, text, border, and accent colors that define the reference page.', 'Compare. Review the colors together and remove values that are duplicates or outside the current visual direction.', 'Save to Palette. Keep the reference-page palette in a project so it can guide a redesign, competitor review, or implementation task.']}
  free={['Pick colors from a website', 'HEX, RGB, and HSL values', '20-color history', 'Single project palette', 'CSS Variables export']}
  pro={['Everything in Free', 'Extract key colors from a page', 'Multiple project palettes', 'Tailwind Config export', 'W3C Design Tokens export']}
  why="a reference-page palette is more useful than a list of isolated HEX values: it keeps the colors you found together so you can compare a brand reference and carry the visual direction into your own work."
  related={[{ href: '/color-picker-chrome-extension', label: 'Use the Chrome color picker' }, { href: '/design-token-generator', label: 'Turn colors into tokens' }, { href: '/pricing', label: 'View Free and Pro pricing' }]}
  faqs={[{ question: 'What is a website color picker?', answer: 'It is a browser-based workflow for collecting colors from a website. TokenTint runs as a Chrome extension so you can sample colors while viewing the reference page.' }, { question: 'How can I build a palette from a competitor website?', answer: 'Sample the key brand, surface, text, border, and accent colors, review them together in history, then save the useful set to a project palette.' }, { question: 'Can TokenTint collect website colors automatically?', answer: 'Pro can extract key colors from the active page as a starting palette. Free focuses on deliberate manual sampling and reuse.' }]}
  visual={{ heroSrc: '/images/screenshots/website-color-picker/hero-reference.png', heroAlt: 'GleeGrove reference website used for a TokenTint competitor color palette', showcaseTitle: 'From reference website to project palette.', heroSize: 'short', showcaseSize: 'tall', showcase: [{ title: 'Start with the reference site', src: '/images/screenshots/website-color-picker/free-reference-2.png', alt: 'Mobile reference website feed used for color research' }, { title: 'Pick colors one at a time', src: '/images/screenshots/website-color-picker/free-picked.png', alt: 'TokenTint free workflow showing a manually picked website color' }, { title: 'Save colors to the project', src: '/images/screenshots/website-color-picker/free-added.png', alt: 'TokenTint free workflow showing colors added to a project' }] }}
  proVisual={{ title: 'Pro workflow: Open → Extract → Organize → Export', description: 'For competitor research and brand references, Pro turns a reference page into a reusable color palette across multiple projects and developer-ready formats.', steps: [{ title: 'Open the reference page', description: 'Start with a specific project or landing page you want to study, then open TokenTint while it is active.', src: '/images/screenshots/website-color-picker/pro-reference-detail.png', alt: 'Dribbble project detail page opened before using TokenTint Pro extraction' }, { title: 'Extract page colors', description: 'Scan the active page for a broader starting palette instead of picking every color one by one.', src: '/images/screenshots/website-color-picker/pro-extracted.png', alt: 'TokenTint Pro showing 20 colors extracted successfully from a webpage' }, { title: 'Organize multiple projects', description: 'Switch between separate palettes for competitors, brands, products, and redesign directions.', src: '/images/screenshots/website-color-picker/pro-projects.png', alt: 'TokenTint Pro project selector showing multiple projects including Competitor Website' }, { title: 'Build a reusable token set', description: 'Choose representative colors and keep several tokens together in the selected project.', src: '/images/screenshots/website-color-picker/pro-tokens.png', alt: 'TokenTint Pro project showing multiple saved color tokens' }, { title: 'Export more formats', description: 'Export the selected palette as CSS Variables, Tailwind Config, or W3C Design Tokens.', src: '/images/screenshots/website-color-picker/pro-exported.png', alt: 'TokenTint Pro W3C Tokens export completed successfully' }] }}
/>; }
